// <auto-generated />
using System;
using CompanyTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CompanyTracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CompanyTracker.Data.Entities.AppliedToCompanyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    b.Property<bool>("CompanyResponded")
                        .HasColumnType("boolean")
                        .HasColumnName("company_responded");

                    b.Property<bool>("IsApplied")
                        .HasColumnType("boolean")
                        .HasColumnName("is_applied");

                    b.HasKey("Id")
                        .HasName("pk_company_applied_check_list");

                    b.HasIndex("CompanyId")
                        .IsUnique()
                        .HasDatabaseName("ix_company_applied_check_list_company_id");

                    b.ToTable("CompanyAppliedCheckList", (string)null);
                });

            modelBuilder.Entity("CompanyTracker.Data.Entities.CompanyContactInfoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("contact_person");

                    b.Property<string>("ContactPersonEmail")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("contact_person_email");

                    b.Property<string>("ContactPersonPhone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("contact_person_phone");

                    b.HasKey("Id")
                        .HasName("pk_company_contact_info");

                    b.HasIndex("CompanyId")
                        .IsUnique()
                        .HasDatabaseName("ix_company_contact_info_company_id");

                    b.ToTable("CompanyContactInfo", (string)null);
                });

            modelBuilder.Entity("CompanyTracker.Data.Entities.CompanyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("city");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("name");

                    b.Property<string>("OrgNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("org_number");

                    b.HasKey("Id")
                        .HasName("pk_company");

                    b.ToTable("Company", (string)null);
                });

            modelBuilder.Entity("CompanyTracker.Data.Entities.AppliedToCompanyEntity", b =>
                {
                    b.HasOne("CompanyTracker.Data.Entities.CompanyEntity", "Company")
                        .WithOne("Applications")
                        .HasForeignKey("CompanyTracker.Data.Entities.AppliedToCompanyEntity", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_company_applied_check_list_company_company_id");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("CompanyTracker.Data.Entities.CompanyContactInfoEntity", b =>
                {
                    b.HasOne("CompanyTracker.Data.Entities.CompanyEntity", "Company")
                        .WithOne("ContactInfos")
                        .HasForeignKey("CompanyTracker.Data.Entities.CompanyContactInfoEntity", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_company_contact_info_company_company_id");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("CompanyTracker.Data.Entities.CompanyEntity", b =>
                {
                    b.Navigation("Applications")
                        .IsRequired();

                    b.Navigation("ContactInfos")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}

